version: 0.0
os: linux

files: # GitHub Actions나 CodeDeploy가 전달한 배포 파일을 EC2의 /home/ubuntu/api-server 아래에 복사
  - source: /
    destination: /home/ubuntu/api-server

# EC2 구조
#  /home/ubuntu/api-server
#  ├── appspec.yml
#  ├── docker-compose.yml
#  ├── docker-compose.prod.yml
#  ├── scripts

hooks:
  ApplicationStop: # 기존 컨테이너 정리
    - location: scripts/cleanup.sh
      timeout: 300
      runas: ubuntu

  AfterInstall: # 파일 복사 끝난 뒤 배포 실행
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu